import { afterEach, describe, expect, test } from 'bun:test';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runDoctor } from './doctor.ts';
import type { ProductPlateManifest } from './types.ts';

const temporaryDirectories: Array<string> = [];

afterEach(async () => {
	await Promise.all(
		temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true }))
	);
});

async function fixture(manifest: ProductPlateManifest) {
	const directory = await mkdtemp(join(tmpdir(), 'product-plate-doctor-'));
	temporaryDirectories.push(directory);
	await writeFile(join(directory, 'product-plate.json'), JSON.stringify(manifest));
	await writeFile(join(directory, 'package.json'), JSON.stringify({ dependencies: {} }));
	await writeFile(join(directory, 'README.md'), '# Launch List\n\nGenerated by Product Plate.\n');
	return directory;
}

const manifest: ProductPlateManifest = {
	schemaVersion: 1,
	generatorVersion: '0.2.0',
	templateVersion: '0.2.0',
	profile: 'prelaunch',
	product: {
		name: 'Launch List',
		slug: 'launch-list',
		description: 'Collect launch interest.',
		productionUrl: null
	},
	theme: 'neutral',
	capabilities: ['landing', 'waitlist', 'legal', 'seo', 'analytics', 'errors', 'email'],
	providers: {
		data: 'convex',
		auth: 'none',
		billing: 'none',
		email: 'resend',
		analytics: 'posthog',
		errors: 'sentry',
		hosting: 'cloudflare-pages'
	}
};

describe('launch doctor', () => {
	test('uses profile-specific checks and never prints secret values', async () => {
		const cwd = await fixture(manifest);
		const secret = 'do-not-print-this-value';
		const result = await runDoctor({
			cwd,
			strict: false,
			env: {
				PUBLIC_CONVEX_URL: 'https://launch-list.convex.cloud',
				PUBLIC_CONVEX_SITE_URL: 'https://launch-list.convex.site',
				WAITLIST_FINGERPRINT_SECRET: secret,
				WAITLIST_EXPORT_SECRET: secret
			}
		});

		expect(result.checks.some((check) => check.id === 'env.BETTER_AUTH_SECRET')).toBe(false);
		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'env.RESEND_API_KEY', status: 'warning' })
		);
		expect(JSON.stringify(result)).not.toContain(secret);
		expect(result.summary.failure).toBe(0);
		expect(result.summary.warning).toBeGreaterThan(0);
		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'content.starter-branding', status: 'pass' })
		);
	});

	test('promotes selected production integration warnings to failures in strict mode', async () => {
		const cwd = await fixture({
			...manifest,
			product: { ...manifest.product, productionUrl: 'https://launch-list.example.com' }
		});
		const result = await runDoctor({ cwd, strict: true, env: {} });

		expect(result.summary.failure).toBeGreaterThan(0);
		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'env.PUBLIC_CONVEX_URL', status: 'failure' })
		);
	});

	test('finds public starter branding, placeholder content, and excluded routes', async () => {
		const cwd = await fixture({
			...manifest,
			product: { ...manifest.product, productionUrl: 'https://launch-list.example.com' }
		});
		await mkdir(join(cwd, 'src/routes/auth/demo'), { recursive: true });
		await writeFile(join(cwd, 'src/routes/auth/demo/+page.svelte'), '<h1>Product Plate demo</h1>');
		const result = await runDoctor({ cwd, strict: true, env: {} });

		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'content.starter-branding', status: 'failure' })
		);
		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'content.legal', status: 'failure' })
		);
		expect(result.checks).toContainEqual(
			expect.objectContaining({ id: 'routes.profile', status: 'failure' })
		);
	});
});
